//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceWork
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string WorkDescription { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string TimeTaken { get; set; }
    }
}
